name: NanoScript
version: 2.0.0
main: dev.nanoscript.NanoScript
api-version: 1.20
description: Lightweight JavaScript scripting engine for Paper servers
authors: [NanoScript]

commands:
  ns:
    description: NanoScript main command
    usage: /ns <load|unload|list> [all|filename]
    aliases: [nanoscript]
    permission: nanoscript.admin

permissions:
  nanoscript.admin:
    description: Full NanoScript access
    default: op
